### ISSUE TITLE
Some ACKs missing from PRs

### ISSUE THREAD

**Issue by jnewbery** [PierreRochard/bitcoin-acks#12]
See 10757 for example. bitcoinacks.com shows just a single concept ACK. It's missing these:

- utACK from ryanofsky: https://github.com/bitcoin/bitcoin/pull/10757#pullrequestreview-73199569
- ACK from jimpo: https://github.com/bitcoin/bitcoin/pull/10757#issuecomment-384129427

I can't load this PR in my browser and get the unicorn. Perhaps that's also causing issues for bitoinacks?

**Comment by PierreRochard** [comment]
1. Both ACKs may be missing due to me only querying for the last 100 comments. I naively thought that would be sufficient! 
2. jimpo's ACK is missing because I'm specifically looking for "tested ack" or "utack". I think a standalone "ack" should be categorized as "tested" as my understanding is that they are synonymous

I'm hoping the graphql api is more resilient than their web interface! 

Thanks for raising this issue, I'll resolve it ASAP

**Comment by moneyball** [comment]
I see a similar issue with https://github.com/bitcoin/bitcoin/pull/10637 and https://bitcoinacks.com/?search=10637

**Comment by PierreRochard** [comment]
My intuition was wrong re: @jnewbery's example of missing ACKs. GitHub differentiates between PR comments and PR reviews, added reviews in https://github.com/PierreRochard/bitcoin-acks/pull/29. 

I think @moneyball's example is a combination of my intuition and the reviews problem: GitHub counts 150 reviews, so I'll have to add pagination and see if that fixes it.

Closing in favor of https://github.com/PierreRochard/bitcoin-acks/issues/13
