### ISSUE TITLE
Filter closed/merged PRs when sorting via ACKs

### ISSUE THREAD

**Issue by fanquake** [PierreRochard/bitcoin-acks#14]
When sorting via ACKs (https://bitcoinacks.com/?desc=1&sort=7), it'd be good to filter out closed or already merged PRs.

**Comment by PierreRochard** [comment]
https://bitcoinacks.com/?flt1_closed_empty=1&desc=1&sort=7&flt0_merged_empty=1

To get there I clicked the "Open PRs" button and then sorted. I could conceivably modify the default root view to be only Open PRs, and then have a second tab that is All PRs, since people are generally only interested in what's Open. I'll give it some more thought and see how usage evolves
