### ISSUE TITLE
Limit body text length

### ISSUE THREAD

**Issue by benthecarman** [PierreRochard/bitcoin-acks#86]
Saw this today
![image](https://user-images.githubusercontent.com/15256660/61748053-ea416580-ad64-11e9-8558-985dd8463a99.png)

**Comment by PierreRochard** [comment]
Ouch, agree, thanks for reporting

**Comment by fjahr** [comment]
I think the body column can be removed from the table in general. When it is truncated so heavily I feel like it usually doesn't add value because I need to look at it in GitHub anyway to get the full picture. What does help sometimes is hovering over it because that lets me see a little more in the popover. I would suggest keeping that functionality but move it on the title column instead.

**Comment by PierreRochard** [comment]
Fixed
